spring:
  application:
    name: vzakhlirb
  datasource:
    url: jdbc:postgresql://localhost:5432/vzakhlirb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Options: none, update, create, create-drop, validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect